In [37]:
import pandas as pd 
import numpy as np

In [38]:
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)

In [39]:
house_df = pd.read_csv("Datasets/houses.csv")
house_df.head()

,property_name,link,society,price,rate,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,noOfFloor,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating,property_id
0,5 Bedroom House for sale in Sector 70A Gurgaon,https://www.99acres.com/5-bhk-bedroom-independ...,Bptp Visionnaire,5.25 Crore,"₹ 20,115/sq.ft.",(242 sq.m.) Plot Area,Plot area 290(242.48 sq.m.),5 Bedrooms,4 Bathrooms,3+ Balconies,Servant Room,"29b, Sector 70A Gurgaon, Gurgaon, Haryana",3 Floors,North-East,0 to 1 Year Old,"['Good Earth City Center 2', 'Kunskapsskolan I...",Do you wish to buy an independent house in sec...,"['1 Wardrobe', '1 Fan', '1 Exhaust Fan', '1 Ge...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment5 out of 5', 'Lifestyle4 out of 5...",K70037724
1,5 Bedroom House for sale in Sector 21A Faridabad,https://www.99acres.com/5-bhk-bedroom-independ...,NaN,5.7 Crore,"₹ 105,751/sq.ft.",(50 sq.m.) Plot Area,Plot area 539(50.07 sq.m.),5 Bedrooms,4 Bathrooms,2 Balconies,"Store Room,Pooja Room,Servant Room","Sector 21A Faridabad, Gurgaon, Haryana",2 Floors,NaN,5 to 10 Year Old,NaN,"Hi, we have an independent house/villa availab...","['1 Water Purifier', '5 Fan', '1 Exhaust Fan',...","['Private Garden / Terrace', 'Park', 'Visitor ...",NaN,E69288322
2,10 Bedroom House for sale in Sushant Lok Phase 1,https://www.99acres.com/10-bhk-bedroom-indepen...,NaN,2.1 Crore,"₹ 38,251/sq.ft.",(51 sq.m.) Plot Area,Plot area 61(51 sq.m.),10 Bedrooms,10 Bathrooms,3+ Balconies,Servant Room,"Sushant Lok Phase 1, Gurgaon, Haryana",5 Floors,West,0 to 1 Year Old,"['Sector 42-43 metro station', 'Huda city cent...","Monthly rental income is rs1,40,000/- Best opt...","['10 Bed', '3 Fan', '10 Geyser', '2 Light', 'N...","['Maintenance Staff', 'Water Storage', 'Visito...","['Environment5 out of 5', 'Lifestyle5 out of 5...",F69536898
3,21 Bedroom House for sale in Sector 54 Gurgaon,https://www.99acres.com/21-bhk-bedroom-indepen...,NaN,5 Crore,"₹ 43,066/sq.ft.",(108 sq.m.) Plot Area,Plot area 129(107.86 sq.m.),21 Bedrooms,21 Bathrooms,3+ Balconies,Servant Room,"Sector 54 Gurgaon, Gurgaon, Haryana",5 Floors,North,1 to 5 Year Old,"['Sector 53-54 metro station', 'Sector 54 chow...","129 sq yd plot size. 5 floors built up , fully...","['1 Water Purifier', '21 Fan', '1 Fridge', '1 ...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment4 out of 5', 'Lifestyle5 out of 5...",R69483164
4,12 Bedroom House for sale in Sushant Lok Phase 1,https://www.99acres.com/12-bhk-bedroom-indepen...,NaN,3 Crore,"₹ 53,763/sq.ft.",(52 sq.m.) Plot Area,Plot area 62(51.84 sq.m.),12 Bedrooms,12 Bathrooms,3+ Balconies,Others,"1228, Sushant Lok Phase 1, Gurgaon, Haryana",5 Floors,West,Within 6 months,"['Sector 42-43 metro station', 'Huda city cent...",Best for investment purpose. Fully furnished b...,"['1 Water Purifier', '1 Fridge', '12 Fan', '1 ...","['Maintenance Staff', 'Water Storage', 'Visito...","['Environment5 out of 5', 'Lifestyle5 out of 5...",M69381272

In [40]:
# check the number of rows and number of columns 
house_df.shape

(1095, 21)

In [41]:
# check for null values 
house_df.isna().sum()

property_name        0
link                 0
society            624
price              127
rate                41
area                 0
areaWithType       108
bedRoom            108
bathroom           108
balcony            108
additionalRoom     506
address             64
noOfFloor          128
facing             421
agePossession      108
nearbyLocations    182
description         59
furnishDetails     352
features           421
rating             188
property_id         59
dtype: int64

In [42]:
# check for duplicate values 
house_df[house_df.duplicated()]

,property_name,link,society,price,rate,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,noOfFloor,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating,property_id
820,4 Bedroom House for sale in Sector 70A Gurgaon,https://www.99acres.com/4-bhk-bedroom-independ...,Bptp Visionnaire,5.4 Crore,"₹ 20,690/sq.ft.",(242 sq.m.) Plot Area,Plot area 290(242.48 sq.m.),4 Bedrooms,5 Bathrooms,3+ Balconies,"Pooja Room,Store Room,Study Room,Servant Room","290 Sqyd Duplex Villa, Sector 70A Gurgaon, Gur...",3 Floors,North,1 to 5 Year Old,"['Good Earth City Center 2', 'Kunskapsskolan I...","Bptp duplex villa 290 sqyd plot size, private ...","['5 Wardrobe', '1 Water Purifier', '6 Geyser',...","['Security / Fire Alarm', 'Feng Shui / Vaastu ...","['Environment5 out of 5', 'Lifestyle4 out of 5...",H68309874
821,4 Bedroom House for sale in C Block Sushant Lo...,https://www.99acres.com/4-bhk-bedroom-independ...,NaN,5.75 Crore,"₹ 29,716/sq.ft.",(180 sq.m.) Plot Area,Plot area 215(179.77 sq.m.),4 Bedrooms,4 Bathrooms,2 Balconies,"Servant Room,Pooja Room,Store Room","C Block Sushant Lok Phase 1, Gurgaon, Haryana",2 Floors,North,10+ Year Old,"['Sector 42-43 metro station', 'Huda city cent...",North facing property\n100 meter from vaipar k...,NaN,"['Feng Shui / Vaastu Compliant', 'High Ceiling...","['Environment4 out of 5', 'Lifestyle4 out of 5...",Z67860202
822,3 Bedroom House for sale in Palam Vihar,https://www.99acres.com/3-bhk-bedroom-independ...,NaN,2.55 Crore,"₹ 16,378/sq.ft.",(145 sq.m.) Plot Area,Plot area 173(144.65 sq.m.),3 Bedrooms,3 Bathrooms,2 Balconies,NaN,"Palam Vihar, Gurgaon, Haryana",2 Floors,South,10+ Year Old,"['Palam Vihar Vyapar kendra', 'Palam triangle'...",173 sq. Yards plot area near by global foyer m...,"['1 Fan', '1 Light', 'No AC', 'No Bed', 'No Ch...",['Park'],"['Environment5 out of 5', 'Lifestyle5 out of 5...",U64835622
823,8 Bedroom House for sale in Palam Vihar,https://www.99acres.com/8-bhk-bedroom-independ...,NaN,5.6 Crore,"₹ 17,284/sq.ft.",(301 sq.m.) Plot Area,Plot area 360(301.01 sq.m.),8 Bedrooms,6 Bathrooms,3+ Balconies,"Pooja Room,Study Room,Servant Room,Store Room","Palam Vihar, Gurgaon, Haryana",NaN,South-West,5 to 10 Year Old,"['Palam Vihar Vyapar kendra', 'Palam triangle'...",360 sq. Yards plot area near by global foyer m...,"['1 Fan', '1 Dining Table', '1 Light', '1 Modu...",NaN,"['Environment5 out of 5', 'Lifestyle5 out of 5...",Z64726172
824,5 Bedroom House for sale in Greenwood City,https://www.99acres.com/5-bhk-bedroom-independ...,NaN,17 Crore,"₹ 37,777/sq.ft.",(418 sq.m.) Plot Area,Plot area 4500(418.06 sq.m.),5 Bedrooms,8 Bathrooms,3+ Balconies,"Pooja Room,Study Room,Servant Room,Store Room","0000, Greenwood City, Gurgaon, Haryana",3 Floors,North-East,1 to 5 Year Old,"['Huda city centre metro station', 'Axis bank ...",Ultra luxury kothi for sale in greenwood city ...,"['1 Water Purifier', '11 Fan', '1 Fridge', '1 ...","['Centrally Air Conditioned', 'Water purifier'...","['Environment4.5 out of 5', 'Lifestyle4 out of...",T68644254
825,4 Bedroom House for sale in Sector 112 Gurgaon,https://www.99acres.com/4-bhk-bedroom-independ...,Experion Windchants3.8 ★,7.99 Crore,"₹ 12,519/sq.ft.",(593 sq.m.) Built-up Area,Built Up area: 6382 (592.91 sq.m.),4 Bedrooms,6 Bathrooms,3 Balconies,"Servant Room,Store Room,Pooja Room","Wp1- Wp-8, Sector 112 Gurgaon, Gurgaon, Haryana",2 Floors,South-East,0 to 1 Year Old,"['Ansal Plaza', 'Dwaraka Expressway', 'First S...",Available for sale 4bhk + servant luxury villa...,"['1 Exhaust Fan', '7 Geyser', '1 Stove', '10 A...","['Security / Fire Alarm', 'Feng Shui / Vaastu ...","['Environment5 out of 5', 'Lifestyle4 out of 5...",H57070296
826,6 Bedroom House for sale in Uppals Southend,https://www.99acres.com/6-bhk-bedroom-independ...,Uppal Southend4.0 ★,3.75 Crore,"₹ 25,562/sq.ft.",(136 sq.m.) Plot Area,Plot area 163(136.29 sq.m.),6 Bedrooms,6 Bathrooms,3 Balconies,Others,"Uppals Southend, Gurgaon, Haryana",3 Floors,East,5 to 10 Year Old,"['Sri Radhe Krishna Temple', 'Icici bank ATM',...",Address...Uppal southend sector 49 w blook \n6...,NaN,"['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment5 out of 5', 'Lifestyle5 out of 5...",M69431990
827,3 Bedroom House for sale in Sector 48 Gurgaon,https://www.99acres.com/3-bhk-bedroom-independ...,Vipul Tatvam Villa,7.25 Crore,"₹ 27,971/sq.ft.",(241 sq.m.) Plot Area,Plot area 288(240.8 sq.m.),3 Bedrooms,4 Bathrooms,2 Balconies,"Servant Room,Study Room,Store Room,Pooja Room","A111, Sector 48 Gurgaon, Gurgaon, Haryana",2 Floors,South,5 to 10 Year Old,"['Athena', 'Star Mall', 'The Sixth Element Sch...",Sector 48 gurgaon is one of gurgaon's most sou...,"['4 Wardrobe', '1 Water Purifier', '12 Fan', '...","['Security / Fire Alarm', 'Feng Shui / Vaastu ...","['Environment4 out of 5', 'Lifestyle4 out of 5...",F70119766
828,4 Bedroom House for sale in Sector 48 Gurgaon,https://www.99acres.com/4-bhk-bedroom-independ...,Vipul Tatvam Villa,8.4 Crore,"₹ 21,000/sq.ft.",(372 sq.m.) Plot Area,Plot area 4000(371.61 sq.m.),4 Bedrooms,5 Bathrooms,3+ Balconies,"Pooja Room,Study Room,Servant Room","Sector 48 Gurgaon, Gurgaon, Haryana",2 Floors,North,5 to 10 Year Old,"['Athena', 'Star Mall', 'The Sixth Element Sch...",Wishing to settle down in an individual house ...,"['5 Wardrobe', '6 Fan', '1 Exhaust Fan', '4 Ge...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment4 out of 5', 'Lifestyle4 out of 5...",K69830898
829,4 Bedroom House for sale in Sector 55 Gurgaon,https://www.99acres.com/4-bhk-bedroom-independ...,NaN,3.55 Crore,"₹ 24,500/sq.ft.",(135 sq.m.) Plot Area,Plot area 161(134.62 sq.m.),4 Bedrooms,4 Bathrooms,3+ Balconies,NaN,"Sector 55 Gurgaon, Gurgaon, Haryana",2 Floors,NaN,10+ Year Old,"['Sector metro station', 'Sector metro station...",For sale 161yd independent house sector 55 gur...,"['6 Wardrobe', '9 Fan', '6 Geyser', '17 Light'...","['Feng Shui / Vaastu Compliant', 'High Ceiling...","['Environment4 out of 5', 'Lifestyle4 out of 5...",L70105542
830,4 Bedroom House for sale in Sector 91 Gurgaon,https://www.99acres.com/4-bhk-bedroom-independ...,DLF New Town Heights3.7 ★,2.5 Crore,"₹ 7,058/sq.ft.",(316 sq.m.) Plot Area,Plot area 3400(315.87 sq.m.),4 Bedrooms,4 Bathrooms,3+ Balconies,"Pooja Room,Study Room,Servant Room,Store Room","Sector 91 Gurgaon, Gurgaon, Haryana",3 Floors,East,5 to 10 Year Old,"['MG Road Metro Station', 'RHM Public School',...","Dlf new town heights, 4bhk independent villa a...","['2 Bed', '7 Wardrobe', '9 Fan', '1 Exhaust Fa...","['Feng Shui / Vaastu Compliant', 'Maintenance ...","['Environment4 out of 5', 'Lifestyle4 out of 5...",A68671054
831,4 Bedroom House for sale in Sector 86 Gurgaon,https://www.99acres.com/4-bhk-bedroom-independ...,DLF New Town Heights 24.0 ★,2.5 Crore,"₹ 7,058/sq.ft.",(316 sq.m.) Plot Area,Plot area 3400(315.87 sq.m.),4 Bedrooms,4 Bathrooms,3+ Balconies,"Study Room,Servant Room,Pooja Room,Store Room","Sector 86 Gurgaon, Gurgaon, Haryana",3 Floors,East,5 to 10 Year Old,"['City Square', 'Vatika Town Square', 'Bharat ...","Dlf new town heights, 4bhk independent villa a...","['2 Bed', '7 Wardrobe', '12 Fan', '1 Exhaust F...","['Security / Fire Alarm', 'Feng Shui / Vaastu ...","['Environment5 out of 5', 'Lifestyle5 out of 5...",I68670824
871,12 Bedroom House for sale in DLF Phase 1,https://www.99acres.com/12-bhk-bedroom-indepen...,Luxury DLF City Floors,8.25 Crore,"₹ 45,833/sq.ft.",(167 sq.m.) Plot Area,Plot area 200(167.23 sq.m.),12 Bedrooms,12 Bathrooms,3+ Balconies,Servant Room,"A Block Dlf-1, DLF Phase 1, Gurgaon, Haryana",4 Floors,North,0 to 1 Year Old,"['Sikandarpur metro station', 'Sikanderpur met...",For sale brand new building having stilt and 4...,"['20 Fan', '1 Exhaust Fan', '12 Geyser', '40 L...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment5 out of 5', 'Lifestyle5 out of 5...",X67105886

In [43]:
# drop the duplicates 
house_df = house_df.drop_duplicates()

In [44]:
# check for missing values
house_df.isnull().sum()

property_name        0
link                 0
society            619
price              127
rate                41
area                 0
areaWithType       108
bedRoom            108
bathroom           108
balcony            108
additionalRoom     504
address             64
noOfFloor          127
facing             420
agePossession      108
nearbyLocations    182
description         59
furnishDetails     350
features           420
rating             188
property_id         59
dtype: int64

In [45]:
# Columns to drop -> property_name, link, property_id
house_df.drop(columns=['link','property_id'], inplace=True)

In [46]:
house_df.head()

,property_name,society,price,rate,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,noOfFloor,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,5 Bedroom House for sale in Sector 70A Gurgaon,Bptp Visionnaire,5.25 Crore,"₹ 20,115/sq.ft.",(242 sq.m.) Plot Area,Plot area 290(242.48 sq.m.),5 Bedrooms,4 Bathrooms,3+ Balconies,Servant Room,"29b, Sector 70A Gurgaon, Gurgaon, Haryana",3 Floors,North-East,0 to 1 Year Old,"['Good Earth City Center 2', 'Kunskapsskolan I...",Do you wish to buy an independent house in sec...,"['1 Wardrobe', '1 Fan', '1 Exhaust Fan', '1 Ge...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment5 out of 5', 'Lifestyle4 out of 5..."
1,5 Bedroom House for sale in Sector 21A Faridabad,NaN,5.7 Crore,"₹ 105,751/sq.ft.",(50 sq.m.) Plot Area,Plot area 539(50.07 sq.m.),5 Bedrooms,4 Bathrooms,2 Balconies,"Store Room,Pooja Room,Servant Room","Sector 21A Faridabad, Gurgaon, Haryana",2 Floors,NaN,5 to 10 Year Old,NaN,"Hi, we have an independent house/villa availab...","['1 Water Purifier', '5 Fan', '1 Exhaust Fan',...","['Private Garden / Terrace', 'Park', 'Visitor ...",NaN
2,10 Bedroom House for sale in Sushant Lok Phase 1,NaN,2.1 Crore,"₹ 38,251/sq.ft.",(51 sq.m.) Plot Area,Plot area 61(51 sq.m.),10 Bedrooms,10 Bathrooms,3+ Balconies,Servant Room,"Sushant Lok Phase 1, Gurgaon, Haryana",5 Floors,West,0 to 1 Year Old,"['Sector 42-43 metro station', 'Huda city cent...","Monthly rental income is rs1,40,000/- Best opt...","['10 Bed', '3 Fan', '10 Geyser', '2 Light', 'N...","['Maintenance Staff', 'Water Storage', 'Visito...","['Environment5 out of 5', 'Lifestyle5 out of 5..."
3,21 Bedroom House for sale in Sector 54 Gurgaon,NaN,5 Crore,"₹ 43,066/sq.ft.",(108 sq.m.) Plot Area,Plot area 129(107.86 sq.m.),21 Bedrooms,21 Bathrooms,3+ Balconies,Servant Room,"Sector 54 Gurgaon, Gurgaon, Haryana",5 Floors,North,1 to 5 Year Old,"['Sector 53-54 metro station', 'Sector 54 chow...","129 sq yd plot size. 5 floors built up , fully...","['1 Water Purifier', '21 Fan', '1 Fridge', '1 ...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment4 out of 5', 'Lifestyle5 out of 5..."
4,12 Bedroom House for sale in Sushant Lok Phase 1,NaN,3 Crore,"₹ 53,763/sq.ft.",(52 sq.m.) Plot Area,Plot area 62(51.84 sq.m.),12 Bedrooms,12 Bathrooms,3+ Balconies,Others,"1228, Sushant Lok Phase 1, Gurgaon, Haryana",5 Floors,West,Within 6 months,"['Sector 42-43 metro station', 'Huda city cent...",Best for investment purpose. Fully furnished b...,"['1 Water Purifier', '1 Fridge', '12 Fan', '1 ...","['Maintenance Staff', 'Water Storage', 'Visito...","['Environment5 out of 5', 'Lifestyle5 out of 5..."

In [47]:
# rename columns
house_df.rename(columns={'rate':'price_per_sqft'},inplace=True)

In [49]:
# cleaning the society column 
house_df["society"].value_counts()

International City by SOBHA Phase 2                  26
Emaar MGF Marbella                                   26
Vipul Tatvam Villa                                   25
International City by Sobha Phase 1                  23
Unitech Uniworld Resorts                             14
DLF City Plots                                       11
DLF City Plots Phase 2                               11
Unitech Espace                                       11
Eldeco Mansionz                                       9
Bptp Visionnaire                                      8
Uppal Southend4.0 ★                                   8
Not Applicable                                        7
Ansals Palam Vihar                                    6
Sushant Lok 1 Builder Floors                          6
Experion Windchants3.8 ★                              5
DLF City Phase 1                                      5
Vatika India Next4.1 ★                                4
nul                                                   4
Unitech Nirvana Birch Court                           4
Ansal Sushant Lok Plots4.1 ★                          4
DLF Alameda                                           4
Ansals Florence Villa                                 4
Unitech Aspen Greens                                  4
DLF New Town Heights 24.0 ★                           4
Vatika Signature Villas                               3
Eros Rosewood City4.0 ★                               3
Sector 14 RWA                                         3
Eros Rosewood Villas                                  3
Palam Vihar Extension West Zone RWA                   3
Malibu Towne                                          3
Housing Board Colony                                  3
BPTP Astaire Gardens3.7 ★                             3
Rattan Garden                                         3
Hans Enclave                                          3
HUDA Ashok Vihar Phase 13.9 ★                         3
Bestech Park View Ananda4.2 ★                         3
SS Aaron Ville                                        3
Silverglades Tarudhan Valley Golf Resort              3
Tata Primanti4.1 ★                                    3
Puri Diplomatic Greens4.0 ★                           3
Central Park Flower Valley                            3
DLF City Plots Phase 3                                3
Anant Raj Estates                                     3
Suncity Essel Towers4.2 ★                             2
IFFCO Nagar and 17B RWA                               2
Bhim Garh Kheri                                       2
Sobha City                                            2
DLF South City 1                                      2
Ansal Sushant Residency                               2
Ardee City3.8 ★                                       2
Signature Global City 92                              2
Satya The Hermitage3.5 ★                              2
Suncity Township4.1 ★                                 2
Unitech Deerwood Chase                                2
Emaar The Palm Springs                                2
Project Mianwali Colony                               2
Nirvana Cedar Crest                                   2
Ansal API Esencia3.7 ★                                2
SS Hibiscus                                           2
Saksham Welfare Association                           2
Unitech Palms South City 1                            2
BPTP Pedestal                                         2
Luxury DLF City Floors                                2
RWA Sector 46                                         2
Sector 38 RWA                                         2
Project Housing Board Colony                          2
Unitech Escape3.8 ★                                   2
DLF City Plots Phase 4                                2
Emaar Emerald Hills4.1 ★                              2
shivpuri                                              2
Spaze Privy3.9 ★                                      2
Om Nagar, Sector-11                                   1
Ireo Victory Valley4.1 ★                              1
Grover Homes Sec 4                                    1
4S Aradhya Homes                                      1
Ansal API Spanish Court                               1
secter 16a daultabad faridabad house no 313           1
Central Park Flower Valley Cerise Floors              1
FLOOR WISE DESIGNER KOTHI                             1
Birla Navya                                           1
Kothi                                                 1
rajendra park sec 105                                 1
nirvana country                                       1
Landmark House                                        1
Smart World Orchard                                   1
cloudnine cottages                                    1
u block dlf phase 3 road no 21                        1
Sector 15 Part 2 RWA                                  1
Nitin Vihar                                           1
Ansal                                                 1
Ashok vihar phase III Extension                       1
Ansal Heights3.2 ★                                    1
rattan vihar rajendra park                            1
Signature Global City 63A                             1
DLF City Plot Phase 3                                 1
Adani Brahma Samsara4.2 ★                             1
sneh vihar                                            1
Ansal Florence Super                                  1
Unitech South City 23.8 ★                             1
Suncity Avenue 76                                     1
patel nager house no 927/5                            1
Huda Floor                                            1
Huda                                                  1
Anant Raj Manor Villas                                1
Sector 57 Huda                                        1
Godrej Meridien                                       1
Ansal Sushant Lok 2                                   1
The Laburnum                                          1
Vatika Independent Floors3.8 ★                        1
Arjun Marg/ Sector- 26 Phase- 1/ Golf Course Road     1
Sector-17C                                            1
DLF Pink Town House4.0 ★                              1
huda sector-56 gurgaon                                1
Satya The Legend3.8 ★                                 1
Prem Kunj                                             1
Ireo Victory Valley4.0 ★                              1
Independent House Sector 45                           1
Ashok Vihar Phase 3 Gurgaon                           1
Farrukhnagar                                          1
Unitech Greenwood City3.6 ★                           1
Vatika The Seven Lamps3.8 ★                           1
Nirvana Country                                       1
Ansal Sushant Lok                                     1
Central Park                                          1
Signature Global City 81                              1
Signature Global City                                 1
DLF Floors Phase 3                                    1
Sheetla Enclave                                       1
SS Omnia                                              1
Bhawani enclave                                       1
Rajendra Park Gurgaon                                 1
Surat nagar phase 2                                   1
Tulip Yellow                                          1
shree krishna homes                                   1
Smart World Gems                                      1
Ganpati Heights Apartment                             1
Hero Homes                                            1
Jacobpura Gurugram                                    1
Anand Garden, Sector-105                              1
DLF Gardencity Enclave                                1
RK Excelo                                             1
DLF The Grove                                         1
Surendra Homes Dayanand Colony                        1
house number B-34                                     1
Ansal Celebrity Homes                                 1
ATS Tourmaline3.9 ★                                   1
Vatika Sovereign Next                                 1
MANOHAR NAGAR                                         1
Laxman vihar phase 2                                  1
Anamika Enclave                                       1
bhim nagar, sector 6                                  1
Emaar MGF The Palm Drive4.1 ★                         1
All Punjabi Welfare Association                       1
Tulip Ivory3.5 ★                                      1
Huda Plots                                            1
DLF Garden City Floors                                1
DLF The Arbour                                        1
Laxmi Garden Sector-11                                1
Shri Shyam Residency                                  1
Anshul                                                1
private house                                         1
Sare Crescent Parc Royal Greens Phase 1               1
Ninex City                                            1
Vipul World3.9 ★                                      1
Greenopolis                                           1
Ansal Esencia Sovereign Floors                        1
Nirmal Enclave, Maruti Kunj Road                      1
jacob pura                                            1
mahavir pura                                          1
Raj Villas                                            1
sector 37                                             1
Shivaji Nagar Residential                             1
Bhim Nagar Society                                    1
DLF City Plot Phase 4                                 1
mian wali                                             1
Sai Kripa Floors 5                                    1
Naman Residency                                       1
Krishna Palace                                        1
DLF New Town Heights3.7 ★                             1
Huda Flats                                            1
Jacobpura                                             1
Indiabulls Centrum Park3.7 ★                          1
Madan puri                                            1
Signature Global Park4.0 ★                            1
ROW HOUSE                                             1
HUDA Plot Sector 38                                   1
My Home                                               1
HUDA Housing Board Colony4.1 ★                        1
Name: society, dtype: int64

In [54]:
house_df["society"].value_counts().shape

(188,)

In [55]:
import re 
house_df['society'] = house_df['society'].apply(lambda name: re.sub(r'\d+(\.\d+)?\s?★', '', str(name)).strip()).str.lower()

In [59]:
house_df["society"].value_counts().shape

(186,)

In [60]:
house_df['society'] = house_df['society'].str.replace('nan','independent')

In [93]:
# cleaning the price column and scale down to same scale (crore)
house_df["price"].value_counts()

3.50     19
5.50     17
6.50     16
6.00     14
0.75     13
5.00     13
4.50     13
0.70     13
8.00     13
0.50     13
0.85     12
7.00     12
8.50     12
0.60     11
1.50     11
4.00     11
9.00     10
0.45     10
2.25     10
2.50     10
0.90     10
10.00    10
2.00      9
12.00     9
0.80      9
9.50      9
1.10      9
1.70      9
0.55      8
11.00     8
1.60      8
1.00      8
6.75      8
4.60      8
12.50     7
1.20      7
3.75      7
0.95      7
1.30      7
0.65      7
0.40      7
2.10      7
1.35      7
7.50      6
3.25      6
10.50     6
1.15      6
4.25      6
2.75      6
6.25      6
3.60      6
5.70      6
1.45      6
16.00     6
2.95      6
13.50     6
1.80      5
2.80      5
5.60      5
0.35      5
3.00      5
4.75      5
1.25      5
0.38      5
7.25      5
15.00     5
0.58      4
4.35      4
0.37      4
0.42      4
18.00     4
9.25      4
4.70      4
1.40      4
1.65      4
2.40      4
5.25      4
8.25      4
3.20      4
13.00     4
3.30      4
5.75      4
11.50     4
17.00     4
5.80      4
6.80      4
0.34      3
0.82      3
7.35      3
0.47      3
5.65      3
4.30      3
1.16      3
0.32      3
3.40      3
0.49      3
1.85      3
0.62      3
0.92      3
5.15      3
0.53      3
2.30      3
8.40      3
7.20      3
2.20      3
3.10      3
19.00     3
20.00     3
6.95      3
1.95      3
0.66      3
4.45      3
2.90      3
6.40      3
3.85      3
1.55      3
1.90      3
0.89      2
1.05      2
26.00     2
14.00     2
3.35      2
3.65      2
10.55     2
8.49      2
9.90      2
15.50     2
10.85     2
3.15      2
2.15      2
3.51      2
6.30      2
2.55      2
0.36      2
11.75     2
3.55      2
1.75      2
0.30      2
0.48      2
11.25     2
0.67      2
4.95      2
19.50     2
7.10      2
11.95     2
10.45     2
3.05      2
9.40      1
5.88      1
10.30     1
8.45      1
6.15      1
31.50     1
9.01      1
12.25     1
10.80     1
2.47      1
2.70      1
2.01      1
3.70      1
4.15      1
2.35      1
7.30      1
18.50     1
8.60      1
4.99      1
27.50     1
8.31      1
6.21      1
1.83      1
9.80      1
18.25     1
5.30      1
5.10      1
3.90      1
4.49      1
0.99      1
18.40     1
1.64      1
9.85      1
7.45      1
9.35      1
3.80      1
9.55      1
6.46      1
4.05      1
8.75      1
6.44      1
23.00     1
2.45      1
1.04      1
7.85      1
7.80      1
25.00     1
1.18      1
7.42      1
4.40      1
9.19      1
2.68      1
2.65      1
6.09      1
1.27      1
11.29     1
4.31      1
4.10      1
11.58     1
15.10     1
8.48      1
8.20      1
7.65      1
5.51      1
3.49      1
2.99      1
22.00     1
0.78      1
8.90      1
0.07      1
4.02      1
3.93      1
0.15      1
4.12      1
1.87      1
0.22      1
3.12      1
2.58      1
3.69      1
8.95      1
13.20     1
0.51      1
0.63      1
1.72      1
1.52      1
0.52      1
11.30     1
7.05      1
8.81      1
7.99      1
10.75     1
7.60      1
10.56     1
5.46      1
7.49      1
12.39     1
5.40      1
8.80      1
0.61      1
7.69      1
8.70      1
6.20      1
5.90      1
5.85      1
5.35      1
6.60      1
4.65      1
6.10      1
0.68      1
8.10      1
1.34      1
0.46      1
2.60      1
3.87      1
1.39      1
0.59      1
0.27      1
14.75     1
1.07      1
9.54      1
17.30     1
18.90     1
24.00     1
7.46      1
3.99      1
6.81      1
18.02     1
0.96      1
0.13      1
2.43      1
5.20      1
0.43      1
0.71      1
1.44      1
3.71      1
0.18      1
3.08      1
0.29      1
0.24      1
0.44      1
0.83      1
0.98      1
3.09      1
0.74      1
0.69      1
2.98      1
Name: price, dtype: int64

In [72]:
house_df = house_df[house_df["price"] != "Price on Request"]

In [76]:
def scale_price(p):
    if type(p) == float:
        return p 
    else:
        if p[1] == "Lac":
            return round(float(p[0])/100, 2) 
        else:
            return round(float(p[0]), 2)

In [82]:
house_df["price"] = house_df["price"].str.split(' ').apply(scale_price)

C:\Users\Omkar\AppData\Local\Temp\ipykernel_8316\4259968038.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  house_df["price"] = house_df["price"].str.split(' ').apply(scale_price)

In [95]:
house_df.head()

,property_name,society,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,noOfFloor,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,5 Bedroom House for sale in Sector 70A Gurgaon,bptp visionnaire,5.25,"₹ 20,115/sq.ft.",(242 sq.m.) Plot Area,Plot area 290(242.48 sq.m.),5 Bedrooms,4 Bathrooms,3+ Balconies,Servant Room,"29b, Sector 70A Gurgaon, Gurgaon, Haryana",3 Floors,North-East,0 to 1 Year Old,"['Good Earth City Center 2', 'Kunskapsskolan I...",Do you wish to buy an independent house in sec...,"['1 Wardrobe', '1 Fan', '1 Exhaust Fan', '1 Ge...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment5 out of 5', 'Lifestyle4 out of 5..."
1,5 Bedroom House for sale in Sector 21A Faridabad,independent,5.70,"₹ 105,751/sq.ft.",(50 sq.m.) Plot Area,Plot area 539(50.07 sq.m.),5 Bedrooms,4 Bathrooms,2 Balconies,"Store Room,Pooja Room,Servant Room","Sector 21A Faridabad, Gurgaon, Haryana",2 Floors,NaN,5 to 10 Year Old,NaN,"Hi, we have an independent house/villa availab...","['1 Water Purifier', '5 Fan', '1 Exhaust Fan',...","['Private Garden / Terrace', 'Park', 'Visitor ...",NaN
2,10 Bedroom House for sale in Sushant Lok Phase 1,independent,2.10,"₹ 38,251/sq.ft.",(51 sq.m.) Plot Area,Plot area 61(51 sq.m.),10 Bedrooms,10 Bathrooms,3+ Balconies,Servant Room,"Sushant Lok Phase 1, Gurgaon, Haryana",5 Floors,West,0 to 1 Year Old,"['Sector 42-43 metro station', 'Huda city cent...","Monthly rental income is rs1,40,000/- Best opt...","['10 Bed', '3 Fan', '10 Geyser', '2 Light', 'N...","['Maintenance Staff', 'Water Storage', 'Visito...","['Environment5 out of 5', 'Lifestyle5 out of 5..."
3,21 Bedroom House for sale in Sector 54 Gurgaon,independent,5.00,"₹ 43,066/sq.ft.",(108 sq.m.) Plot Area,Plot area 129(107.86 sq.m.),21 Bedrooms,21 Bathrooms,3+ Balconies,Servant Room,"Sector 54 Gurgaon, Gurgaon, Haryana",5 Floors,North,1 to 5 Year Old,"['Sector 53-54 metro station', 'Sector 54 chow...","129 sq yd plot size. 5 floors built up , fully...","['1 Water Purifier', '21 Fan', '1 Fridge', '1 ...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment4 out of 5', 'Lifestyle5 out of 5..."
4,12 Bedroom House for sale in Sushant Lok Phase 1,independent,3.00,"₹ 53,763/sq.ft.",(52 sq.m.) Plot Area,Plot area 62(51.84 sq.m.),12 Bedrooms,12 Bathrooms,3+ Balconies,Others,"1228, Sushant Lok Phase 1, Gurgaon, Haryana",5 Floors,West,Within 6 months,"['Sector 42-43 metro station', 'Huda city cent...",Best for investment purpose. Fully furnished b...,"['1 Water Purifier', '1 Fridge', '12 Fan', '1 ...","['Maintenance Staff', 'Water Storage', 'Visito...","['Environment5 out of 5', 'Lifestyle5 out of 5..."

In [104]:
# cleaning the price_per_sqft column 
house_df["price_per_sqft"] = house_df["price_per_sqft"].str.split(' ').str.get(1).str.split('/').str.get(0).str.replace(',', '').str.strip().astype("float")

C:\Users\Omkar\AppData\Local\Temp\ipykernel_8316\734886135.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  house_df["price_per_sqft"] = house_df["price_per_sqft"].str.split(' ').str.get(1).str.split('/').str.get(0).str.replace(',', '').str.strip().astype("float")

In [106]:
# cleaning the bedRoom column 
house_df["bedRoom"].value_counts()

4 Bedrooms     232
5 Bedrooms     194
3 Bedrooms     146
2 Bedrooms      88
6 Bedrooms      81
9 Bedrooms      45
1 Bedroom       38
8 Bedrooms      33
7 Bedrooms      31
12 Bedrooms     28
10 Bedrooms     21
16 Bedrooms     12
13 Bedrooms      4
18 Bedrooms      2
19 Bedrooms      2
11 Bedrooms      2
20 Bedrooms      1
21 Bedrooms      1
36 Bedrooms      1
34 Bedrooms      1
14 Bedrooms      1
Name: bedRoom, dtype: int64

In [114]:
# check for null values 
house_df[house_df["bedRoom"].isnull()]

,property_name,society,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,noOfFloor,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
60,4 Bedroom House for sale in Sector 86 Gurgaon,dlf new town heights,NaN,7718.0,(297 sq.m.) Plot Area,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
61,8 Bedroom House for sale in B1 Block Sector 57...,independent,NaN,25535.0,(135 sq.m.) Plot Area,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
62,6 Bedroom House for sale in DLF Phase 1,independent,NaN,1859.0,(420 sq.m.) Plot Area,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
63,6 Bedroom House for sale in Sushant Lok Phase 3,ansal sushant residency,NaN,17037.0,(251 sq.m.) Plot Area,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
64,6 Bedroom House for sale in Sushant Lok Phase 3,ansals florence villa,NaN,10579.0,(321 sq.m.) Plot Area,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
65,4 Bedroom House for sale in DLF Phase 4,independent,NaN,42194.0,(264 sq.m.) Plot Area,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
66,8 Bedroom House for sale in Uppals Southend,independent,NaN,15625.0,(268 sq.m.) Plot Area,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
67,6 Bedroom House for sale in Uppals Southend,uppal southend,NaN,15278.0,(268 sq.m.) Plot Area,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
68,4 Bedroom House for sale in Sector 48 Gurgaon,vipul tatvam villa,NaN,201388.0,(33 sq.m.) Plot Area,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
69,4 Bedroom House for sale in Malibu Town,independent,NaN,17187.0,(54 sq.m.) Plot Area,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
70,5 Bedroom House for sale in Sector 33 Gurgaon,unitech uniworld resorts,NaN,NaN,(420 sq.m.) Plot Area,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
71,5 Bedroom House for sale in DLF Phase 1,independent,NaN,44444.0,(418 sq.m.) Plot Area,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
72,3 Bedroom House for sale in South City 1,dlf south city 1,NaN,18928.0,(201 sq.m.) Plot Area,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75,5 Bedroom House for sale in Sector 109 Gurgaon,international city by sobha phase 2,NaN,13622.0,(467-681 sq.m.) Built-up Area,NaN,NaN,NaN,NaN,NaN,"Sector 109 Gurgaon, Gurgaon, Haryana",NaN,NaN,NaN,"['Dwarka Sector 21 Metro Station', 'Pacific D2...",International city by sobha phase 2 in sector-...,NaN,NaN,"['Environment5 out of 5', 'Lifestyle4 out of 5..."
76,4 Bedroom House for sale in Sector 109 Gurgaon,international city by sobha phase 2,NaN,13909.0,(384-392 sq.m.) Built-up Area,NaN,NaN,NaN,NaN,NaN,"Sector 109 Gurgaon, Gurgaon, Haryana",NaN,NaN,NaN,"['Dwarka Sector 21 Metro Station', 'Pacific D2...",International city by sobha phase 2 in sector-...,NaN,NaN,"['Environment5 out of 5', 'Lifestyle4 out of 5..."
79,5 Bedroom House for sale in Sector 66 Gurgaon,emaar mgf marbella,NaN,16058.0,(606-754 sq.m.) Built-up Area,NaN,NaN,NaN,NaN,NaN,"Sector 66 Gurgaon, Gurgaon, Haryana",NaN,NaN,NaN,"['Sector 55-56 Rapid Metro Station', 'HUB 66',...","Emaar mgf marbella in sector-66, gurgaon by em...",NaN,NaN,"['Environment3 out of 5', 'Lifestyle4 out of 5..."
80,4 Bedroom House for sale in Sector 66 Gurgaon,emaar mgf marbella,NaN,16058.0,(521 sq.m.) Built-up Area,NaN,NaN,NaN,NaN,NaN,"Sector 66 Gurgaon, Gurgaon, Haryana",NaN,NaN,NaN,"['Sector 55-56 Rapid Metro Station', 'HUB 66',...","Emaar mgf marbella in sector-66, gurgaon by em...",NaN,NaN,"['Environment3 out of 5', 'Lifestyle4 out of 5..."
81,5 Bedroom House for sale in Sector 109 Gurgaon,international city by sobha phase 2,NaN,13623.0,(467-681 sq.m.) Built-up Area,NaN,NaN,NaN,NaN,NaN,"Sector 109 Gurgaon, Gurgaon, Haryana",NaN,NaN,NaN,"['Dwarka Sector 21 Metro Station', 'Pacific D2...",International city by sobha phase 2 in sector-...,NaN,NaN,"['Environment5 out of 5', 'Lifestyle4 out of 5..."
82,4 Bedroom House for sale in Sector 109 Gurgaon,international city by sobha phase 2,NaN,13910.0,(294-418 sq.m.) Built-up Area,NaN,NaN,NaN,NaN,NaN,"Sector 109 Gurgaon, Gurgaon, Haryana",NaN,NaN,NaN,"['Dwarka Sector 21 Metro Station', 'Pacific D2...",International city by sobha phase 2 in sector-...,NaN,NaN,"['Environment5 out of 5', 'Lifestyle4 out of 5..."
83,3 Bedroom House for sale in Sector 109 Gurgaon,international city by sobha phase 2,NaN,13910.0,(293 sq.m.) Built-up Area,NaN,NaN,NaN,NaN,NaN,"Sector 109 Gurgaon, Gurgaon, Haryana",NaN,NaN,NaN,"['Dwarka Sector 21 Metro Station', 'Pacific D2...",International city by sobha phase 2 in sector-...,NaN,NaN,"['Environment5 out of 5', 'Lifestyle4 out of 5..."
84,4 Bedroom House for sale in Sector 112 Gurgaon,experion windchants,NaN,12027.0,(590-687 sq.m.) Built-up Area,NaN,NaN,NaN,NaN,NaN,"Sector 112 Gurgaon, Gurgaon, Haryana",NaN,NaN,NaN,"['Ansal Plaza', 'Dwaraka Expressway', 'First S...","Experion windchants in sector 112, gurgaon by ...",NaN,NaN,"['Environment5 out of 5', 'Lifestyle4 out of 5..."
85,4 Bedroom House for sale in Sector 66 Gurgaon,emaar mgf marbella,NaN,15700.0,(521 sq.m.) Built-up Area,NaN,NaN,NaN,NaN,NaN,"Sector 66 Gurgaon, Gurgaon, Haryana",NaN,NaN,NaN,"['Sector 55-56 Rapid Metro Station', 'HUB 66',...","Emaar mgf marbella in sector-66, gurgaon by em...",NaN,NaN,"['Environment3 out of 5', 'Lifestyle4 out of 5..."
86,5 Bedroom House for sale in Sector 66 Gurgaon,emaar mgf marbella,NaN,19708.0,(606 sq.m.) Built-up Area,NaN,NaN,NaN,NaN,NaN,"Sector 66 Gurgaon, Gurgaon, Haryana",NaN,NaN,NaN,"['Sector 55-56 Rapid Metro Station', 'HUB 66',...","Emaar mgf marbella in sector-66, gurgaon by em...",NaN,NaN,"['Environment3 out of 5', 'Lifestyle4 out of 5..."
87,4 Bedroom House for sale in Sector 66 Gurgaon,emaar mgf marbella,NaN,16039.0,(521 sq.m.) Built-up Area,NaN,NaN,NaN,NaN,NaN,"Sector 66 Gurgaon, Gurgaon, Haryana",NaN,NaN,NaN,"['Sector 55-56 Rapid Metro Station', 'HUB 66',...","Emaar mgf marbella in sector-66, gurgaon by em...",NaN,NaN,"['Environment3 out of 5', 'Lifestyle4 out of 5..."
88,3 Bedroom House for sale in Sector 73 Gurgaon,dlf alameda,NaN,13331.0,(543 sq.m.) Built-up Area,NaN,NaN,NaN,NaN,NaN,"Sector 73 Gurgaon, Gurgaon, Haryana",NaN,NaN,NaN,"['Raheja Mall', 'Captain Chandan Lal Marg', 'B...","Dlf alameda in sector-73 gurgaon, gurgaon by d...",NaN,NaN,NaN
89,5 Bedroom House for sale in Sector 109 Gurgaon,international city by sobha phase 1,NaN,11100.0,(468-681 sq.m.) Built-up Area,NaN,NaN,NaN,NaN,NaN,"Sector 109 Gurgaon, Gurgaon, Haryana",NaN,NaN,NaN,"['Dwarka sector 21 metro station', 'Pacific D2...","With just 6 villas per acre, international cit...",NaN,NaN,"['Environment5 out of 5', 'Lifestyle4 out of 5..."
90,4 Bedroom House for sale in Sector 109 Gurgaon,international city by sobha phase 1,NaN,11100.0,(292-358 sq.m.) Built-up Area,NaN,NaN,NaN,NaN,NaN,"Sector 109 Gurgaon, Gurgaon, Haryana",NaN,NaN,NaN,"['Dwarka sector 21 metro station', 'Pacific D2...","With just 6 villas per acre, international cit...",NaN,NaN,"['Environment5 out of 5', 'Lifestyle4 out of 5..."
91,3 Bedroom House for sale in Sector 109 Gurgaon,international city by sobha phase 1,NaN,11100.0,(293 sq.m.) Built-up Area,NaN,NaN,NaN,NaN,NaN,"Sector 109 Gurgaon, Gurgaon, Haryana",NaN,NaN,NaN,"['Dwarka sector 21 metro station', 'Pacific D2...","With just 6 villas per acre, international cit...",NaN,NaN,"['Environment5 out of 5', 'Lifestyle4 out of 5..."
94,5 Bedroom House for sale in Sector 66 Gurgaon,emaar mgf marbella,NaN,19708.0,(606 sq.m.) Built-up Area,NaN,NaN,NaN,NaN,NaN,"Sector 66 Gurgaon, Gurgaon, Haryana",NaN,NaN,NaN,"['Sector 55-56 Rapid Metro Station', 'HUB 66',...","Emaar mgf marbella in sector-66, gurgaon by em...",NaN,NaN,"['Environment3 out of 5', 'Lifestyle4 out of 5..."
95,4 Bedroom House for sale in Sector 66 Gurgaon,emaar mgf marbella,NaN,16039.0,(521 sq.m.) Built-up Area,NaN,NaN,NaN,NaN,NaN,"Sector 66 Gurgaon, Gurgaon, Haryana",NaN,NaN,NaN,"['Sector 55-56 Rapid Metro Station', 'HUB 66',...","Emaar mgf marbella in sector-66, gurgaon by em...",NaN,NaN,"['Environment3 out of 5', 'Lifestyle4 out of 5..."
96,4 Bedroom House for sale in Sector 109 Gurgaon,international city by sobha phase 1,NaN,11100.0,(325 sq.m.) Built-up Area,NaN,NaN,NaN,NaN,NaN,"Sector 109 Gurgaon, Gurgaon, Haryana",NaN,NaN,NaN,"['Dwarka sector 21 metro station', 'Pacific D2...","With just 6 villas per acre, international cit...",NaN,NaN,"['Environment5 out of 5', 'Lifestyle4 out of 5..."
97,3 Bedroom House for sale in Sector 109 Gurgaon,international city by sobha phase 1,NaN,11100.0,(293 sq.m.) Built-up Area,NaN,NaN,NaN,NaN,NaN,"Sector 109 Gurgaon, Gurgaon, Haryana",NaN,NaN,NaN,"['Dwarka sector 21 metro station', 'Pacific D2...","With just 6 villas per acre, international cit...",NaN,NaN,"['Environment5 out of 5', 'Lifestyle4 out of 5..."
98,4 Bedroom House for sale in Sector 23 Gurgaon,all punjabi welfare association,NaN,16999.0,(139-279 sq.m.) Built-up Area,NaN,NaN,NaN,NaN,NaN,"Sector 23 Gurgaon, Gurgaon, Haryana",NaN,NaN,NaN,"['HUDA Sector 23 Market', 'Palam triangle', 'R...",All punjabi welfare association in sector-23 g...,NaN,NaN,"['Environment4 out of 5', 'Lifestyle5 out of 5..."
99,4 Bedroom House for sale in Sector 72 Gurgaon,tata primanti,NaN,10714.0,(650-790 sq.m.) Built-up Area,NaN,NaN,NaN,NaN,NaN,"Sector 72 Gurgaon, Gurgaon, Haryana",NaN,NaN,NaN,"['Sector 55-56 Metro Station', 'Omaxe City Cen...","Tata primanti in sector-72, gurgaon by tata ho...",NaN,NaN,"['Environment4.5 out of 5', 'Lifestyle4.5 out ..."
100,4 Bedroom House for sale in Sector 112 Gurgaon,experion windchants,NaN,12027.0,(590-687 sq.m.) Built-up Area,NaN,NaN,NaN,NaN,NaN,"Sector 112 Gurgaon, Gurgaon, Haryana",NaN,NaN,NaN,"['Ansal Plaza', 'Dwaraka Expressway', 'First S...","Experion windchants in sector 112, gurgaon by ...",NaN,NaN,"['Environment5 out of 5', 'Lifestyle4 out of 5..."
101,5 Bedroom House for sale in Sector 63A Gurgaon,aindependentt raj estates,NaN,NaN,(251-704 sq.m.) Built-up Area,NaN,NaN,NaN,NaN,NaN,"Sector 63A Gurgaon, Gurgaon, Haryana",NaN,NaN,NaN,"['Sector 55-56 Metro Station', 'Paras Trinity ...","Anant raj estates in sector-63a gurgaon, gurga...",NaN,NaN,"['Environment4 out of 5', 'Lifestyle4 out of 5..."
102,3 Bedroom House for sale in Sector 63A Gurgaon,aindependentt raj estates,NaN,NaN,(211 sq.m.) Built-up Area,NaN,NaN,NaN,NaN,NaN,"Sector 63A Gurgaon, Gurgaon, Haryana",NaN,NaN,NaN,"['Sector 55-56 Metro Station', 'Paras Trinity ...","Anant raj estates in sector-63a gurgaon, gurga...",NaN,NaN,"['Environment4 out of 5', 'Lifestyle4 out of 5..."
105,4 Bedroom House for sale in Sector 48 Gurgaon,vipul tatvam villa,NaN,18750.0,(372-441 sq.m.) Built-up Area,NaN,NaN,NaN,NaN,NaN,"Sector 48 Gurgaon, Gurgaon, Haryana",NaN,NaN,NaN,"['Athena', 'Star Mall', 'The Sixth Element Sch...","Vipul tatvam villa in sector-48 gurgaon, gurga...",NaN,NaN,"['Environment4 out of 5', 'Lifestyle4 out of 5..."
106,3 Bedroom House for sale in Sector 48 Gurgaon,vipul tatvam villa,NaN,19000.0,(279 sq.m.) Built-up Area,NaN,NaN,NaN,NaN,NaN,"Sector 48 Gurgaon, Gurgaon, Haryana",NaN,NaN,NaN,"['Athena', 'Star Mall', 'The Sixth Element Sch...","Vipul tatvam villa in sector-48 gurgaon, gurga...",NaN,NaN,"['Environment4 out of 5', 'Lifestyle4 out of 5..."
107,5 Bedroom House for sale in Sector 48 Gurgaon,vipul tatvam villa,NaN,27793.0,(571-711 sq.m.) Built-up Area,NaN,NaN,NaN,NaN,NaN,"Sector 48 Gurgaon, Gurgaon, Haryana",NaN,NaN,NaN,"['Athena', 'Star Mall', 'The Sixth Element Sch...","Vipul tatvam villa in sector-48 gurgaon, gurga...",NaN,NaN,"['Environment4 out of 5', 'Lifestyle4 out of 5..."
108,4 Bedroom House for sale in Sector 48 Gurgaon,vipul tatvam villa,NaN,22006.0,(372-441 sq.m.) Built-up Area,NaN,NaN,NaN,NaN,NaN,"Sector 48 Gurgaon, Gurgaon, Haryana",NaN,NaN,NaN,"['Athena', 'Star Mall', 'The Sixth Element Sch...","Vipul tatvam villa in sector-48 gurgaon, gurga...",NaN,NaN,"['Environment4 out of 5', 'Lifestyle4 out of 5..."
109,3 Bedroom House for sale in Sector 48 Gurgaon,vipul tatvam villa,NaN,19000.0,(279 sq.m.) Built-up Area,NaN,NaN,NaN,NaN,NaN,"Sector 48 Gurgaon, Gurgaon, Haryana",NaN,NaN,NaN,"['Athena', 'Star Mall', 'The Sixth Element Sch...","Vipul tatvam villa in sector-48 gurgaon, gurga...",NaN,NaN,"['Environment4 out of 5', 'Lifestyle4 out of 5..."
110,3 Bedroom House for sale in Sector 73 Gurgaon,dlf alameda,NaN,13333.0,(543 sq.m.) Built-up Area,NaN,NaN,NaN,NaN,NaN,"Sector 73 Gurgaon, Gurgaon, Haryana",NaN,NaN,NaN,"['Raheja Mall', 'Captain Chandan Lal Marg', 'B...","Dlf alameda in sector-73 gurgaon, gurgaon by d...",NaN,NaN,NaN
111,5 Bedroom House for sale in Sector 48 Gurgaon,eldeco mansionz,NaN,22222.0,(293-381 sq.m.) Built-up Area,NaN,NaN,NaN,NaN,NaN,"Sector 48 Gurgaon, Gurgaon, Haryana",NaN,NaN,NaN,"['Sri Radhe Krishna Temple', 'Icici bank ATM',...","Eldeco mansionz in sector-48 gurgaon, gurgaon ...",NaN,NaN,"['Environment4 out of 5', 'Lifestyle4 out of 5..."
112,4 Bedroom House for sale in Sector 48 Gurgaon,eldeco mansionz,NaN,28760.0,(207 sq.m.) Built-up Area,NaN,NaN,NaN,NaN,NaN,"Sector 48 Gurgaon, Gurgaon, Haryana",NaN,NaN,NaN,"['Sri Radhe Krishna Temple', 'Icici bank ATM',...","Eldeco mansionz in sector-48 gurgaon, gurgaon ...",NaN,NaN,"['Environment4 out of 5', 'Lifestyle4 out of 5..."
113,3 Bedroom House for sale in Sector 48 Gurgaon,eldeco mansionz,NaN,16975.0,(301 sq.m.) Built-up Area,NaN,NaN,NaN,NaN,NaN,"Sector 48 Gurgaon, Gurgaon, Haryana",NaN,NaN,NaN,"['Sri Radhe Krishna Temple', 'Icici bank ATM',...","Eldeco mansionz in sector-48 gurgaon, gurgaon ...",NaN,NaN,"['Environment4 out of 5', 'Lifestyle4 out of 5..."
115,5 Bedroom House for sale in Sector 66 Gurgaon,emaar mgf marbella,NaN,16058.0,(606-754 sq.m.) Built-up Area,NaN,NaN,NaN,NaN,NaN,"Sector 66 Gurgaon, Gurgaon, Haryana",NaN,NaN,NaN,"['Sector 55-56 Rapid Metro Station', 'HUB 66',...","Emaar mgf marbella in sector-66, gurgaon by em...",NaN,NaN,"['Environment3 out of 5', 'Lifestyle4 out of 5..."
116,4 Bedroom House for sale in Sector 66 Gurgaon,emaar mgf marbella,NaN,15700.0,(521 sq.m.) Built-up Area,NaN,NaN,NaN,NaN,NaN,"Sector 66 Gurgaon, Gurgaon, Haryana",NaN,NaN,NaN,"['Sector 55-56 Rapid Metro Station', 'HUB 66',...","Emaar mgf marbella in sector-66, gurgaon by em...",NaN,NaN,"['Environment3 out of 5', 'Lifestyle4 out of 5..."
117,4 Bedroom House for sale in Sector 65 Gurgaon,emaar emerald hills,NaN,NaN,(183 sq.m.) Built-up Area,NaN,NaN,NaN,NaN,NaN,"Sector 65 Gurgaon, Gurgaon, Haryana",NaN,NaN,NaN,"['Emerald Plaza Shopping Mall', 'Southern Peri...","Emaar emerald hills in sector-65 gurgaon, gurg...",NaN,NaN,"['Environment4 out of 5', 'Lifestyle4 out of 5..."
118,4 Bedroom House for sale in Sector-33 Sohna,central park flower valley,NaN,NaN,(344 sq.m.) Built-up Area,NaN,NaN,NaN,NaN,NaN,"Sector-33 Sohna, Gurgaon, Haryana",NaN,NaN,NaN,"['Golf Course Extension Rd', 'Rajiv Chowk - So...","Central park flower valley in sector-33 sohna,...",NaN,NaN,NaN
123,5 Bedroom House for sale in Sector 111 Gurgaon,puri diplomatic greens,NaN,12828.0,(650 sq.m.) Built-up Area,NaN,NaN,NaN,NaN,NaN,"Sector 111 Gurgaon, Gurgaon, Haryana",NaN,NaN,NaN,"['Dwarka Sector 21 Metro Station', 'Gurgaon Dr...","Puri diplomatic greens in sector-111 gurgaon, ...",NaN,NaN,NaN
124,5 Bedroom House for sale in Sector 111 Gurgaon,puri diplomatic greens,NaN,12842.0,(650 sq.m.) Built-up Area,NaN,NaN,NaN,NaN,NaN,"Sector 111 Gurgaon, Gurgaon, Haryana",NaN,NaN,NaN,"['Dwarka Sector 21 Metro Station', 'Gurgaon Dr...","Puri diplomatic greens in sector-111 gurgaon, ...",NaN,NaN,NaN
128,3 Bedroom House for sale in Sector 73 Gurgaon,dlf alameda,NaN,NaN,(543 sq.m.) Built-up Area,NaN,NaN,NaN,NaN,NaN,"Sector 73 Gurgaon, Gurgaon, Haryana",NaN,NaN,NaN,"['Raheja Mall', 'Captain Chandan Lal Marg', 'B...","Dlf alameda in sector-73 gurgaon, gurgaon by d...",NaN,NaN,NaN
178,4 Bedroom House for sale in Nirvana Country,unitech nirvana birch court,NaN,32407.0,(301 sq.m.) Plot Area,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
179,5 Bedroom House for sale in Sector 63 Gurgaon,aindependentt raj manor villas,NaN,37037.0,(251 sq.m.) Plot Area,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
180,4 Bedroom House for sale in Sector 81 Gurgaon,bestech park view aindependentda,NaN,8181.0,(511 sq.m.) Plot Area,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
181,12 Bedroom House for sale in Sector 56 Gurgaon,independent,NaN,43333.0,(251 sq.m.) Plot Area,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
182,2 Bedroom House for sale in Laxman Vihar,huda ashok vihar phase,NaN,7777.0,(42 sq.m.) Plot Area,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
183,4 Bedroom House for sale in Ghamroj,independent,NaN,481.0,(995 sq.m.) Plot Area,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
184,8 Bedroom House for sale in Palam Vihar Extension,independent,NaN,3452.0,(390 sq.m.) Built-up Area,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
185,1 Bedroom House for sale in Sector 57 Gurgaon,independent,NaN,24444.0,(209 sq.m.) Plot Area,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
186,3 Bedroom House for sale in Sector 8 Gurgaon,independent,NaN,100000.0,(6 sq.m.) Built-up Area,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
187,5 Bedroom House for sale in Patel Nagar,independent,NaN,13071.0,(142 sq.m.) Plot Area,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
188,6 Bedroom House for sale in Patel Nagar,patel nager house no 927/5,NaN,11111.0,(142 sq.m.) Plot Area,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
189,12 Bedroom House for sale in Pratap Nagar,independent,NaN,102941.0,(16 sq.m.) Plot Area,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
190,12 Bedroom House for sale in South City 1,independent,NaN,29321.0,(301 sq.m.) Plot Area,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
191,5 Bedroom House for sale in Sector 23 Gurgaon,independent,NaN,21242.0,(171 sq.m.) Plot Area,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
192,8 Bedroom House for sale in DLF Phase 3,independent,NaN,24912.0,(264 sq.m.) Built-up Area,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
193,7 Bedroom House for sale in DLF Phase 4,dlf city plots phase 4,NaN,255555.0,(33 sq.m.) Plot Area,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
194,5 Bedroom House for sale in Maruti Kunj,independent,NaN,9259.0,(151 sq.m.) Plot Area,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
195,5 Bedroom House for sale in Rajiv Chowk,hans enclave,NaN,4333.0,(139 sq.m.) Plot Area,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
196,3 Bedroom House for sale in Laxman Vihar,huda ashok vihar phase,NaN,11784.0,(84 sq.m.) Plot Area,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
197,4 Bedroom House for sale in Madanpuri,independent,NaN,13359.0,(70 sq.m.) Plot Area,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
198,7 Bedroom House for sale in Sector 11 Gurgaon,independent,NaN,197080.0,(13 sq.m.) Plot Area,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
199,5 Bedroom House for sale in Shivaji Nagar,independent,NaN,13131.0,(184 sq.m.) Plot Area,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
308,5 Bedroom House for sale in Sector 81 Gurgaon,bestech park view aindependentda,NaN,NaN,(509-543 sq.m.) Built-up Area,NaN,NaN,NaN,NaN,NaN,"Sector 81 Gurgaon, Gurgaon, Haryana",NaN,NaN,NaN,"['Metro Station Kankrola sec 87', 'Sapphire 83...","Bestech park view ananda in sector-81 gurgaon,...",NaN,NaN,"['Environment4.5 out of 5', 'Lifestyle4 out of..."
312,4 Bedroom House for sale in Sector-33 Sohna,central park flower valley,NaN,NaN,(344 sq.m.) Built-up Area,NaN,NaN,NaN,NaN,NaN,"Sector-33 Sohna, Gurgaon, Haryana",NaN,NaN,NaN,"['Golf Course Extension Rd', 'Rajiv Chowk - So...","Central park flower valley in sector-33 sohna,...",NaN,NaN,NaN

In [117]:
# drop the rows where bedRoom is NaN 
house_df = house_df[~house_df["bedRoom"].isnull()]

In [118]:
house_df.shape

(964, 19)

In [123]:
# now clean the column 
house_df["bedRoom"] = house_df["bedRoom"].str.split().str.get(0).astype("int")

C:\Users\Omkar\AppData\Local\Temp\ipykernel_8316\2950117465.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  house_df["bedRoom"] = house_df["bedRoom"].str.split().str.get(0).astype("int")

In [128]:
# cleaning the bathroom column 
house_df["bathroom"].isnull().sum() # there is no missing value

0

In [129]:
house_df["bathroom"].value_counts()

4 Bathrooms     228
3 Bathrooms     165
5 Bathrooms     137
2 Bathrooms     114
6 Bathrooms      82
1 Bathroom       65
9 Bathrooms      42
7 Bathrooms      39
8 Bathrooms      28
12 Bathrooms     22
10 Bathrooms     11
16 Bathrooms      8
18 Bathrooms      4
13 Bathrooms      4
11 Bathrooms      4
20 Bathrooms      3
17 Bathrooms      3
14 Bathrooms      2
21 Bathrooms      1
36 Bathrooms      1
34 Bathrooms      1
Name: bathroom, dtype: int64

In [133]:
house_df["bathroom"] = house_df["bathroom"].str.split().str.get(0).astype("int")

C:\Users\Omkar\AppData\Local\Temp\ipykernel_8316\2434443507.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  house_df["bathroom"] = house_df["bathroom"].str.split().str.get(0).astype("int")

In [136]:
# cleaning the balcony column 
house_df["balcony"].value_counts()

3+ Balconies    365
2 Balconies     220
3 Balconies     159
No Balcony      115
1 Balcony       105
Name: balcony, dtype: int64

In [139]:
# check for null values 
house_df["balcony"].isnull().sum() # there are no null values

0

In [145]:
house_df["balcony"] = house_df["balcony"].str.split().str.get(0).str.replace('+', '').str.replace('No', '0').astype("int")

C:\Users\Omkar\AppData\Local\Temp\ipykernel_8316\965416463.py:1: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
  house_df["balcony"] = house_df["balcony"].str.split().str.get(0).str.replace('+', '').str.replace('No', '0').astype("int")
C:\Users\Omkar\AppData\Local\Temp\ipykernel_8316\965416463.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  house_df["balcony"] = house_df["balcony"].str.split().str.get(0).str.replace('+', '').str.replace('No', '0').astype("int")

In [147]:
house_df["balcony"].value_counts()

3    524
2    220
0    115
1    105
Name: balcony, dtype: int64

In [151]:
# cleaning additionalRoom column (this column needs feature engineering)
house_df["additionalRoom"].value_counts()

Servant Room                                     81
Pooja Room,Study Room,Servant Room,Store Room    60
Others                                           58
Pooja Room                                       38
Pooja Room,Study Room,Servant Room               33
Pooja Room,Study Room,Servant Room,Others        32
Store Room                                       31
Pooja Room,Servant Room                          24
Study Room                                       19
Study Room,Servant Room                          19
Servant Room,Store Room                          15
Pooja Room,Study Room                            11
Pooja Room,Store Room                            11
Pooja Room,Others                                11
Servant Room,Pooja Room                           8
Servant Room,Others                               8
Pooja Room,Store Room,Study Room,Servant Room     8
Pooja Room,Servant Room,Store Room                7
Store Room,Servant Room                           6
Study Room,Servant Room,Pooja Room,Store Room     6
Servant Room,Pooja Room,Store Room                6
Pooja Room,Servant Room,Others                    5
Servant Room,Study Room                           5
Servant Room,Study Room,Pooja Room,Store Room     5
Study Room,Pooja Room,Servant Room                5
Servant Room,Store Room,Pooja Room                4
Study Room,Servant Room,Store Room                4
Pooja Room,Servant Room,Study Room,Store Room     4
Study Room,Servant Room,Store Room,Pooja Room     4
Pooja Room,Study Room,Others                      4
Store Room,Pooja Room                             4
Pooja Room,Study Room,Store Room                  3
Study Room,Servant Room,Pooja Room                3
Study Room,Others                                 3
Study Room,Pooja Room,Servant Room,Store Room     3
Study Room,Pooja Room,Store Room,Servant Room     2
Pooja Room,Study Room,Store Room,Servant Room     2
Study Room,Servant Room,Others                    2
Store Room,Pooja Room,Study Room,Servant Room     2
Study Room,Pooja Room                             2
Store Room,Pooja Room,Study Room                  2
Store Room,Pooja Room,Servant Room                2
Servant Room,Study Room,Pooja Room                2
Study Room,Pooja Room,Store Room                  2
Study Room,Store Room                             1
Study Room,Store Room,Pooja Room                  1
Store Room,Pooja Room,Servant Room,Study Room     1
Servant Room,Store Room,Study Room,Pooja Room     1
Servant Room,Study Room,Store Room,Pooja Room     1
Store Room,Servant Room,Study Room,Pooja Room     1
Pooja Room,Store Room,Servant Room                1
Servant Room,Others,Pooja Room                    1
Study Room,Store Room,Servant Room,Pooja Room     1
Store Room,Study Room,Servant Room                1
Store Room,Servant Room,Pooja Room                1
Study Room,Others,Servant Room                    1
Name: additionalRoom, dtype: int64

In [154]:
# check for null values 
house_df["additionalRoom"][house_df["additionalRoom"].isnull()]

20      NaN
34      NaN
50      NaN
57      NaN
77      NaN
93      NaN
119     NaN
120     NaN
130     NaN
134     NaN
135     NaN
136     NaN
137     NaN
138     NaN
154     NaN
167     NaN
203     NaN
204     NaN
206     NaN
207     NaN
212     NaN
213     NaN
218     NaN
219     NaN
220     NaN
221     NaN
222     NaN
223     NaN
224     NaN
226     NaN
228     NaN
229     NaN
230     NaN
231     NaN
232     NaN
233     NaN
234     NaN
235     NaN
236     NaN
237     NaN
238     NaN
241     NaN
242     NaN
243     NaN
244     NaN
245     NaN
246     NaN
247     NaN
249     NaN
251     NaN
252     NaN
253     NaN
254     NaN
255     NaN
256     NaN
259     NaN
261     NaN
262     NaN
265     NaN
266     NaN
267     NaN
268     NaN
269     NaN
270     NaN
271     NaN
272     NaN
273     NaN
274     NaN
275     NaN
276     NaN
279     NaN
280     NaN
281     NaN
283     NaN
284     NaN
285     NaN
286     NaN
289     NaN
290     NaN
291     NaN
293     NaN
294     NaN
297     NaN
298     NaN
299     NaN
300     NaN
301     NaN
302     NaN
303     NaN
304     NaN
305     NaN
306     NaN
307     NaN
310     NaN
311     NaN
314     NaN
316     NaN
317     NaN
318     NaN
322     NaN
323     NaN
324     NaN
332     NaN
333     NaN
334     NaN
335     NaN
336     NaN
337     NaN
340     NaN
343     NaN
344     NaN
345     NaN
346     NaN
347     NaN
348     NaN
349     NaN
350     NaN
351     NaN
352     NaN
357     NaN
370     NaN
374     NaN
375     NaN
376     NaN
377     NaN
378     NaN
379     NaN
380     NaN
381     NaN
383     NaN
385     NaN
386     NaN
388     NaN
389     NaN
390     NaN
391     NaN
392     NaN
393     NaN
394     NaN
395     NaN
397     NaN
399     NaN
401     NaN
403     NaN
404     NaN
405     NaN
406     NaN
407     NaN
408     NaN
409     NaN
411     NaN
412     NaN
414     NaN
415     NaN
416     NaN
418     NaN
419     NaN
422     NaN
423     NaN
424     NaN
425     NaN
426     NaN
427     NaN
433     NaN
435     NaN
436     NaN
438     NaN
440     NaN
443     NaN
444     NaN
447     NaN
448     NaN
450     NaN
451     NaN
453     NaN
454     NaN
455     NaN
456     NaN
457     NaN
458     NaN
460     NaN
461     NaN
462     NaN
463     NaN
466     NaN
468     NaN
469     NaN
470     NaN
472     NaN
475     NaN
476     NaN
478     NaN
480     NaN
483     NaN
484     NaN
485     NaN
486     NaN
487     NaN
488     NaN
489     NaN
490     NaN
492     NaN
493     NaN
495     NaN
498     NaN
499     NaN
500     NaN
501     NaN
502     NaN
504     NaN
505     NaN
506     NaN
509     NaN
510     NaN
515     NaN
516     NaN
518     NaN
519     NaN
520     NaN
522     NaN
523     NaN
524     NaN
525     NaN
526     NaN
527     NaN
528     NaN
530     NaN
531     NaN
532     NaN
533     NaN
534     NaN
535     NaN
536     NaN
537     NaN
538     NaN
539     NaN
540     NaN
541     NaN
542     NaN
543     NaN
544     NaN
545     NaN
546     NaN
547     NaN
548     NaN
549     NaN
550     NaN
551     NaN
552     NaN
553     NaN
554     NaN
556     NaN
557     NaN
558     NaN
560     NaN
562     NaN
563     NaN
564     NaN
565     NaN
566     NaN
567     NaN
568     NaN
570     NaN
571     NaN
572     NaN
574     NaN
575     NaN
576     NaN
577     NaN
578     NaN
579     NaN
580     NaN
582     NaN
583     NaN
584     NaN
585     NaN
586     NaN
587     NaN
588     NaN
589     NaN
590     NaN
591     NaN
592     NaN
593     NaN
596     NaN
597     NaN
598     NaN
601     NaN
602     NaN
603     NaN
604     NaN
606     NaN
607     NaN
608     NaN
609     NaN
610     NaN
611     NaN
613     NaN
614     NaN
615     NaN
616     NaN
617     NaN
618     NaN
619     NaN
620     NaN
622     NaN
623     NaN
625     NaN
626     NaN
629     NaN
630     NaN
631     NaN
632     NaN
633     NaN
635     NaN
636     NaN
638     NaN
639     NaN
640     NaN
641     NaN
642     NaN
643     NaN
645     NaN
646     NaN
648     NaN
649     NaN
650     NaN
651     NaN
652     NaN
653     NaN
654     NaN
655     NaN
657     NaN
659     NaN
661     NaN
663     NaN
664     NaN
665     NaN
666     NaN
669     NaN
673     NaN
674     NaN
675     NaN
676     NaN
678     NaN
682     NaN
684     NaN
685     NaN
686     NaN
688     NaN
691     NaN
704     NaN
707     NaN
723     NaN
734     NaN
736     NaN
739     NaN
773     NaN
789     NaN
790     NaN
791     NaN
811     NaN
817     NaN
818     NaN
841     NaN
855     NaN
860     NaN
864     NaN
865     NaN
880     NaN
887     NaN
903     NaN
904     NaN
940     NaN
941     NaN
969     NaN
972     NaN
973     NaN
975     NaN
976     NaN
981     NaN
1008    NaN
1049    NaN
1065    NaN
1067    NaN
1071    NaN
Name: additionalRoom, dtype: object

In [155]:
# fill the NaN with not available 
house_df["additionalRoom"].fillna("not available", inplace=True)

C:\Users\Omkar\AppData\Local\Temp\ipykernel_8316\4215099782.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  house_df["additionalRoom"].fillna("not available", inplace=True)

In [162]:
house_df["additionalRoom"][house_df["additionalRoom"] == "not available"]

20      not available
34      not available
50      not available
57      not available
77      not available
93      not available
119     not available
120     not available
130     not available
134     not available
135     not available
136     not available
137     not available
138     not available
154     not available
167     not available
203     not available
204     not available
206     not available
207     not available
212     not available
213     not available
218     not available
219     not available
220     not available
221     not available
222     not available
223     not available
224     not available
226     not available
228     not available
229     not available
230     not available
231     not available
232     not available
233     not available
234     not available
235     not available
236     not available
237     not available
238     not available
241     not available
242     not available
243     not available
244     not available
245     not available
246     not available
247     not available
249     not available
251     not available
252     not available
253     not available
254     not available
255     not available
256     not available
259     not available
261     not available
262     not available
265     not available
266     not available
267     not available
268     not available
269     not available
270     not available
271     not available
272     not available
273     not available
274     not available
275     not available
276     not available
279     not available
280     not available
281     not available
283     not available
284     not available
285     not available
286     not available
289     not available
290     not available
291     not available
293     not available
294     not available
297     not available
298     not available
299     not available
300     not available
301     not available
302     not available
303     not available
304     not available
305     not available
306     not available
307     not available
310     not available
311     not available
314     not available
316     not available
317     not available
318     not available
322     not available
323     not available
324     not available
332     not available
333     not available
334     not available
335     not available
336     not available
337     not available
340     not available
343     not available
344     not available
345     not available
346     not available
347     not available
348     not available
349     not available
350     not available
351     not available
352     not available
357     not available
370     not available
374     not available
375     not available
376     not available
377     not available
378     not available
379     not available
380     not available
381     not available
383     not available
385     not available
386     not available
388     not available
389     not available
390     not available
391     not available
392     not available
393     not available
394     not available
395     not available
397     not available
399     not available
401     not available
403     not available
404     not available
405     not available
406     not available
407     not available
408     not available
409     not available
411     not available
412     not available
414     not available
415     not available
416     not available
418     not available
419     not available
422     not available
423     not available
424     not available
425     not available
426     not available
427     not available
433     not available
435     not available
436     not available
438     not available
440     not available
443     not available
444     not available
447     not available
448     not available
450     not available
451     not available
453     not available
454     not available
455     not available
456     not available
457     not available
458     not available
460     not available
461     not available
462     not available
463     not available
466     not available
468     not available
469     not available
470     not available
472     not available
475     not available
476     not available
478     not available
480     not available
483     not available
484     not available
485     not available
486     not available
487     not available
488     not available
489     not available
490     not available
492     not available
493     not available
495     not available
498     not available
499     not available
500     not available
501     not available
502     not available
504     not available
505     not available
506     not available
509     not available
510     not available
515     not available
516     not available
518     not available
519     not available
520     not available
522     not available
523     not available
524     not available
525     not available
526     not available
527     not available
528     not available
530     not available
531     not available
532     not available
533     not available
534     not available
535     not available
536     not available
537     not available
538     not available
539     not available
540     not available
541     not available
542     not available
543     not available
544     not available
545     not available
546     not available
547     not available
548     not available
549     not available
550     not available
551     not available
552     not available
553     not available
554     not available
556     not available
557     not available
558     not available
560     not available
562     not available
563     not available
564     not available
565     not available
566     not available
567     not available
568     not available
570     not available
571     not available
572     not available
574     not available
575     not available
576     not available
577     not available
578     not available
579     not available
580     not available
582     not available
583     not available
584     not available
585     not available
586     not available
587     not available
588     not available
589     not available
590     not available
591     not available
592     not available
593     not available
596     not available
597     not available
598     not available
601     not available
602     not available
603     not available
604     not available
606     not available
607     not available
608     not available
609     not available
610     not available
611     not available
613     not available
614     not available
615     not available
616     not available
617     not available
618     not available
619     not available
620     not available
622     not available
623     not available
625     not available
626     not available
629     not available
630     not available
631     not available
632     not available
633     not available
635     not available
636     not available
638     not available
639     not available
640     not available
641     not available
642     not available
643     not available
645     not available
646     not available
648     not available
649     not available
650     not available
651     not available
652     not available
653     not available
654     not available
655     not available
657     not available
659     not available
661     not available
663     not available
664     not available
665     not available
666     not available
669     not available
673     not available
674     not available
675     not available
676     not available
678     not available
682     not available
684     not available
685     not available
686     not available
688     not available
691     not available
704     not available
707     not available
723     not available
734     not available
736     not available
739     not available
773     not available
789     not available
790     not available
791     not available
811     not available
817     not available
818     not available
841     not available
855     not available
860     not available
864     not available
865     not available
880     not available
887     not available
903     not available
904     not available
940     not available
941     not available
969     not available
972     not available
973     not available
975     not available
976     not available
981     not available
1008    not available
1049    not available
1065    not available
1067    not available
1071    not available
Name: additionalRoom, dtype: object

In [164]:
# convert all the information to lower case 
house_df['additionalRoom'] = house_df['additionalRoom'].str.lower()

C:\Users\Omkar\AppData\Local\Temp\ipykernel_8316\3401983893.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  house_df['additionalRoom'] = house_df['additionalRoom'].str.lower()

In [169]:
# cleaning the noOffloor column 
house_df["noOfFloor"].isnull().sum()

19

In [174]:
house_df["noOfFloor"] = house_df["noOfFloor"].str.split().str.get(0)

C:\Users\Omkar\AppData\Local\Temp\ipykernel_8316\1864996880.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  house_df["noOfFloor"] = house_df["noOfFloor"].str.split().str.get(0)

In [180]:
# rename the column noOffloor 
house_df.rename(columns={'noOfFloor':'floorNum'},inplace=True)

C:\Users\Omkar\AppData\Local\Temp\ipykernel_8316\2477989599.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  house_df.rename(columns={'noOfFloor':'floorNum'},inplace=True)

In [182]:
# cleaning the facing column 
house_df['facing'].fillna('NA',inplace=True)

C:\Users\Omkar\AppData\Local\Temp\ipykernel_8316\547547446.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  house_df['facing'].fillna('NA',inplace=True)

In [183]:
# adding the extra column area from price and price_per_sqft
house_df['area'] = round((house_df['price']*10000000)/house_df['price_per_sqft'])

C:\Users\Omkar\AppData\Local\Temp\ipykernel_8316\2824938305.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  house_df['area'] = round((house_df['price']*10000000)/house_df['price_per_sqft'])

In [185]:
# insert the new column which tells the property type 
house_df.insert(loc=1,column='property_type', value='house')

In [186]:
house_df.head()

,property_name,property_type,society,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,5 Bedroom House for sale in Sector 70A Gurgaon,house,bptp visionnaire,5.25,20115.0,2610.0,Plot area 290(242.48 sq.m.),5,4,3,servant room,"29b, Sector 70A Gurgaon, Gurgaon, Haryana",3,North-East,0 to 1 Year Old,"['Good Earth City Center 2', 'Kunskapsskolan I...",Do you wish to buy an independent house in sec...,"['1 Wardrobe', '1 Fan', '1 Exhaust Fan', '1 Ge...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment5 out of 5', 'Lifestyle4 out of 5..."
1,5 Bedroom House for sale in Sector 21A Faridabad,house,independent,5.70,105751.0,539.0,Plot area 539(50.07 sq.m.),5,4,2,"store room,pooja room,servant room","Sector 21A Faridabad, Gurgaon, Haryana",2,NA,5 to 10 Year Old,NaN,"Hi, we have an independent house/villa availab...","['1 Water Purifier', '5 Fan', '1 Exhaust Fan',...","['Private Garden / Terrace', 'Park', 'Visitor ...",NaN
2,10 Bedroom House for sale in Sushant Lok Phase 1,house,independent,2.10,38251.0,549.0,Plot area 61(51 sq.m.),10,10,3,servant room,"Sushant Lok Phase 1, Gurgaon, Haryana",5,West,0 to 1 Year Old,"['Sector 42-43 metro station', 'Huda city cent...","Monthly rental income is rs1,40,000/- Best opt...","['10 Bed', '3 Fan', '10 Geyser', '2 Light', 'N...","['Maintenance Staff', 'Water Storage', 'Visito...","['Environment5 out of 5', 'Lifestyle5 out of 5..."
3,21 Bedroom House for sale in Sector 54 Gurgaon,house,independent,5.00,43066.0,1161.0,Plot area 129(107.86 sq.m.),21,21,3,servant room,"Sector 54 Gurgaon, Gurgaon, Haryana",5,North,1 to 5 Year Old,"['Sector 53-54 metro station', 'Sector 54 chow...","129 sq yd plot size. 5 floors built up , fully...","['1 Water Purifier', '21 Fan', '1 Fridge', '1 ...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment4 out of 5', 'Lifestyle5 out of 5..."
4,12 Bedroom House for sale in Sushant Lok Phase 1,house,independent,3.00,53763.0,558.0,Plot area 62(51.84 sq.m.),12,12,3,others,"1228, Sushant Lok Phase 1, Gurgaon, Haryana",5,West,Within 6 months,"['Sector 42-43 metro station', 'Huda city cent...",Best for investment purpose. Fully furnished b...,"['1 Water Purifier', '1 Fridge', '12 Fan', '1 ...","['Maintenance Staff', 'Water Storage', 'Visito...","['Environment5 out of 5', 'Lifestyle5 out of 5..."

In [187]:
house_df.shape

(964, 20)

In [188]:
house_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 964 entries, 0 to 1090
Data columns (total 20 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   property_name    964 non-null    object
 1   property_type    964 non-null    object
 2   society          964 non-null    object
 3   price            945 non-null    float64
 4   price_per_sqft   945 non-null    float64
 5   area             945 non-null    float64
 6   areaWithType     964 non-null    object
 7   bedRoom          964 non-null    int32
 8   bathroom         964 non-null    int32
 9   balcony          964 non-null    int32
 10  additionalRoom   964 non-null    object
 11  address          959 non-null    object
 12  floorNum         945 non-null    object
 13  facing           964 non-null    object
 14  agePossession    964 non-null    object
 15  nearbyLocations  848 non-null    object
 16  description      964 non-null    object
 17  furnishDetails   729 non-null    object
 18  features         662 non-null    object
 19  rating           843 non-null    object
dtypes: float64(3), int32(3), object(14)
memory usage: 146.9+ KB

In [189]:
# export the dataset 
house_df.to_csv("house_cleaned_phase1.csv", index=False)

In [191]:
sample_house = pd.read_csv("house_cleaned_phase1.csv")

In [192]:
sample_house.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 964 entries, 0 to 963
Data columns (total 20 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   property_name    964 non-null    object
 1   property_type    964 non-null    object
 2   society          964 non-null    object
 3   price            945 non-null    float64
 4   price_per_sqft   945 non-null    float64
 5   area             945 non-null    float64
 6   areaWithType     964 non-null    object
 7   bedRoom          964 non-null    int64
 8   bathroom         964 non-null    int64
 9   balcony          964 non-null    int64
 10  additionalRoom   964 non-null    object
 11  address          959 non-null    object
 12  floorNum         945 non-null    float64
 13  facing           661 non-null    object
 14  agePossession    964 non-null    object
 15  nearbyLocations  848 non-null    object
 16  description      964 non-null    object
 17  furnishDetails   729 non-null    object
 18  features         662 non-null    object
 19  rating           843 non-null    object
dtypes: float64(4), int64(3), object(13)
memory usage: 150.8+ KB